branches:
  only:
  - master

dist: focal

language: node_js

node_js:
  - 16

cache: npm

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
  fqdn: bailly.app
